### PR TITLE
Watchlist

### PR DESCRIPTION
**Pull request by shoeffner**
This feature adds a local (i.e. device-local using localStorage) watchlist for courses.
- Adds checkboxes to the lectures.
- Selecting a checkbox adds a course to the watchlist, unselected removes it.
- Toggling between "favorites" and non-favorites using a button hides unselected courses.
- Favorites and view setting are localStorage-persistent.
- Changing the schedule list links to not trigger on checkbox clicks.
- Changing the schedule list links to feel like "big buttons" instead of textual links by using a gray background instead of blue underlines.
- Disables this feature if no javascript is available.
- Preview works without javascript.
- Import/Export via prompts, passing a simple list of course ids: `47,51,52`. This has to be copied and transfered manually, but avoids the trouble of detecting URLs and import intends etc.
- The daytoggler bar is now a `tools` bar and contains the favorite toggle and the import export buttons.
- The details pages also feature a button to star the lectures / indicate their favorite status.

Main page with only favorites and hover effect:
Main page with only favorites and hover effec

Details page with favorite star (if unfavorited, the box is empty):
Details page with favorite star

~I am still thinking about how to better position/style the toggle button, especially to also represent the current state. But this has to wait until tomorrow, just wanted to give you an opportunity to give some feedback on the feature: Do we want it? Or not?~

~P.S.: I was thinking about sharing etc. via a link - but that quickly seems to be out of scope for now, so device-local is the best I will be able to offer in time.~

### CODE REVIEW

**Comment by jspricke** [comment]
This sounds really awesome! Will try to review before Friday.
Regarding exporting it, shouldn't a bitmask work?

**Comment by shoeffner** [comment]
Rebased to include the details changes from master.

Regarding export: Yes, a bitmask would work, even just a comma separated list like `13,34,59` etc would work (probably with much less effort). The problems is to build a good import/export mechanism, but I will think about it.

**Comment by jspricke** [comment]
I thought encoding it into the URL.

**Comment by shoeffner** [comment]
I am afraid of people sharing links with their favorites and overwriting their friends' local storages if we simply import it from a URL. So there should be a way to distinguish between "URL imported" and "loaded from localStorage" etc., or do you think it's not a problem? I thought maybe a little input field which can be overwritten and then loaded/stored etc. might be a better idea.

**Comment by shoeffner** [comment]
Import and export are now handled via very basic `prompt()`s. This way importing/exporting is explicit and not implicit via a URL or anything.

I also made all buttons look the same. I will edit a full list of features into the first post, including images.

**Comment by jspricke** [comment]
I love it a lot!
Some small comments:
- [x] the star in details doesn't display on my computer (probably I don't have the symbol). Maybe replace it by a normal checkbox.
- [x] Sort the exorted list.
- [x] More a general thing: provide an option to hide all buttons and checkboxes for the big screens.
- [x] Provide a clear watchlist button.

**Comment by shoeffner** [comment]
Thanks for your feedback, I'll work on it now!

Is a get parameter for hiding the buttons okay? I will create another PR
for that.

edit: I included it here. See below.

**Comment by shoeffner** [comment]
Alright, adding `?hidetools` hides the tools and checkboxes without interfering with anything else.

**Comment by jspricke** [comment]
Thanks and see you tomorrow!

**Pull request merged**
