### PR TITLE
WIP CSS grid

### PR DESCRIPTION
**Pull request by jspricke**
Hey guys, I implemented a first version. If someone wants to improve it, feel
free (but I will try to work on it as well):

- [x] Improve design (fonts, color..., spacing).
- [x] Fix (or get rid of) jquery to reload parts of the page.
- [x] Improve find a better solution for /ik/hacks

### CODE REVIEW

**Comment by shoeffner** [comment]
What is /ik/hacks supposed to mean? Is it some kind of event?

We could just have "Evening" as the title for that column. We would need something to handle starting times for evening events properly though, at the moment the `sprintf` for those cases is not working as I would expect it to work (even though there is now the `/ik/hack & Community` string.

**Comment by jspricke** [comment]
Thanks a lot Sebastian! I'm fine with merging this (will do tomorrow if no one objects or is faster ;) ).
Regarding /ik/hacks, @sweetneuron could comment on it maybe.

**Comment by sweetneuron** [comment]
@shoeffner /ik/hacks are events organized by participants, such as ignite talks, workshops, and discussions... they are less formal and more interactive... basically, everything that already happens at IK anyway, can be announced as an /ik/hack so that more people can know about it...

**Comment by jspricke** [comment]
As they could be at any time, I would propose to extend the current hack in https://github.com/jspricke/ik-infoscreen/blob/css_grid/index.php#L36 to always map them to a fitting column (start time in slot?).

**Comment by sweetneuron** [comment]
I agree. Maybe it would be best to list them into the block, where /ik/hack start time > previous block end time, e.g., Jan Kirchners hack will start on Sun 1330, so we could list it in the 1430 block (and after the regular IK lectures). I think, when you are done with the morning courses, you would check the schedule to see what is up after lunch and find the /ik/hack. Would that make sense for you?

**Comment by shoeffner** [comment]
So there can be more /ik/hacks in the future? How likely is it, that they will occur during lunch break times? If it's many events during that time slot, maybe we should have a sixth column for lunch breaks? I will build the "start time in slot" solution, as that will give more flexibility anyways. For events during lunch time I will for now place them in the 14:30 block, as @sweetneuron suggested.

@sweetneuron Do you know if we can expect all /ik/hacks to have an empty instructor-field but the title of the format "/ik/hack - instructor - title"?

**Comment by sweetneuron** [comment]
Excellent, thank you.

Yes, there will be more like these. There will be also an announcement in a couple of days.

It is not unlikely that they happen during lunch breaks. Lunch breaks are rather long so some people might want to use them for hacks. The basic idea is that people can organize meetings whenever they want to. So there could be someone who wants to organize a morning meditation session at 0800 as well. That is why I am not really sure if we want to add additional columns (i.e., lunch, morning) to the time table that may be empty most of the time.

Yes, instructor will remain empty. I am not fully sure that we will keep the "/ik/hack - instructor - title"  format but for the time being, I think it will stay like this.

**Comment by shoeffner** [comment]
Will /ik/hacks also happen during coffe breaks?

**Comment by sweetneuron** [comment]
It could be possible. E.g., a short meeting to organize next steps.

**Comment by shoeffner** [comment]
Then let's merge this and I will create a new PR for the ik/hacks. Maybe it's a good idea to have them in their own column and mark each individual entry when it's active, like I currently mark the columns...? Let's discuss it over there.

**Comment by sweetneuron** [comment]
Excellent, I think this is the most useful and flexible way.

**Pull request merged**
